#! /Library/Frameworks/Python.framework/Versions/3.8/bin/python3

import sys

def main(a):
    power = 0
    numStr = ''
    while 2 ** (power + 1) < a:
        power += 1
    while power >= 0:
        if 2 ** power < a + 1:
            numStr += '1'
            a -= 2 ** power
        else:
            numStr += '0'
        power -= 1
    return int(numStr)
print(main(int(sys.argv[1])))
